# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps: 
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          
      - name: Remote check out new master
        run: ssh staging 'cd movie-picker-nx && git fetch && git reset --hard origin/master'
      # TODO: Is it possible to push artifacts from build step?
      - name: Remote build 
        run: ssh staging 'cd movie-picker-nx && npm i && npm run build'
      - name: Move front-end to appropriate folders
        run: scp -r -i ~/.ssh/staging.key ./dist ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_SSH_HOST }}:dist
#         run: ssh staging 'rm -rf /var/www/front && mv movie-picker-nx/dist/movie-picker/* /var/www/front/*'
      - name: Move back-end
#         run: ssh staging 'rm -rf /var/www/back && mv movie-picker-nx/dist/api/* /var/www/back/*'
      - name: Restart back-end
        run: ssh staging 'pm2 restart www'
